# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: deploy to aliyun

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f src/requirements.txt ]; then pip3 install -r src/requirements.txt --no-build-isolation; fi
      env:
          CI: true
# Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
          SSH_PRIVATE_KEY: ${{ secrets.ALY_SSH_TOKEN }}
          ARGS: "-avz --delete"
          SOURCE: "server/app"
          REMOTE_HOST: ${{ secrets.ALY_SSH_HOST }}
          REMOTE_USER: "root"
          TARGET: "/home/test/src/app"
